apiVersion: apps/v1
kind: Deployment
metadata:
  name: argus-hls-service
  labels:
    app: argus-hls-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argus-hls-service
  template:
    metadata:
      labels:
        app: argus-hls-service
    spec:
      containers:
      - name: hls-server
        image: <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/argus-hls-service:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: videos-volume
          mountPath: /app/videos
      volumes:
      - name: videos-volume
        hostPath:
          path: /path/to/your/videos  # Replace with the actual path on your host
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: argus-hls-service
spec:
  type: LoadBalancer
  selector:
    app: argus-hls-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
